version: '3'
services:
  influxdb:
    image: influxdb
    restart: always
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: temperature
      INFLUXDB_ADMIN_USER: user
      INFLUXDB_ADMIN_PASSWORD: password

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_AUTH_BASIC_ENABLED: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_INSTALL_PLUGINS: "grafana-clock-panel"
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
    depends_on:
      - influxdb
