version: '3'
services:
  influxdb:
    image: influxdb:1.8
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/mnt/shared/code/influxdb2
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=Password1
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_AUTH_BASIC_ENABLED: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_INSTALL_PLUGINS: "grafana-clock-panel"
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
    depends_on:
      - influxdb
    networks:
      - mynetwork

  myapp:
    build:
      
      context: .
      dockerfile: Dockerfile
    depends_on:
      - influxdb
    networks:
      - mynetwork
networks:
  mynetwork:

volumes:
  influxdb-storage: